# Generated by Django 5.2.4 on 2025-09-11 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0002_hero_email_contato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='email_contato',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
