# Generated by Django 5.2.6 on 2025-09-18 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0003_alter_hero_email_contato'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_herois/'),
        ),
    ]
